# Generated by Django 3.2.7 on 2021-09-29 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stat', models.DateField(default=datetime.date(2021, 9, 29))),
                ('spent', models.IntegerField()),
                ('get_money', models.IntegerField(default=0)),
            ],
        ),
    ]
